# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyGitHubTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyGitHubTracker
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxAppState'
  pod 'Then'
  pod 'SnapKit'
  pod 'KeychainSwift'

  target 'MyGitHubTrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyGitHubTrackerUITests' do
    # Pods for testing
  end

end
